urls.py
from django.urls import path
from . import views

app_name = 'plan_of_care'

urlpatterns = [
    path('plan_of_care/<int:pk>', views.PlanOfCareList.as_view(), name='plan-list'),
    path('plan_of_care/create/', views.PlanOfCareCreate.as_view(), name='plan-create'),
    path('plan_of_care/create/<int:pk>', views.PlanOfCareCreate.as_view(), name='plan-create'),
    path('plan_of_care/<int:pk>/update', views.PlanOfCareUpdate.as_view(), name='plan-update'),
    path('plan_of_care/<int:pk>/delete', views.PlanOfCareDelete.as_view(), name='plan-delete'),
]

models.py
from django.db import models
from geriatrics.models import Admission
from kardex.models import Diagnosis

# Create your models here.
class CareProvider(models.Model):
    name = models.CharField(max_length=70)
    role = models.CharField(max_length=10, blank=True)
    
    class Meta:
        ordering = ['name',]

    def __str__(self):
        return f'{self.name} - {self.role}' 

class PlanOfCare(models.Model):
    date = models.DateField(auto_now=False, null=False, blank=False)
    admission = models.ForeignKey(Admission, on_delete=models.CASCADE, limit_choices_to={'discharged': False}, null=True)
    problem = models.ForeignKey(Diagnosis, on_delete=models.CASCADE, null=True)
    goal = models.TextField()
    action_plan = models.TextField()
    responsible_person = models.ManyToManyField(CareProvider)

    class Meta:
        ordering = ['-date',]
        verbose_name_plural = 'Plans of care'

    def __str__(self):
        return f'{self.date} - for {self.problem}'

forms.py
from django import forms
from .models import PlanOfCare
from bootstrap_modal_forms.forms import BSModalModelForm

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class PlanOfCareCreateForm(BSModalModelForm):
    class Meta:
        model = PlanOfCare
        fields = '__all__' 
        widgets = { 'date': DateInput(), }

views.py
from django.views.generic import ListView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import PlanOfCare
from .forms import PlanOfCareCreateForm
from geriatrics.models import Admission

from .tables import PlanOfCareTable

from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView

class PlanOfCareList(LoginRequiredMixin, ListView):
    model = PlanOfCare
    template_name = 'plan_of_care/includes/plan_of_care.html'

    def get_context_data(self, *args, **kwargs):
        request = self.request
        context = super(PlanOfCareList, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            try:
                admission = Admission.objects.get(id=self.kwargs['pk'])
                data = PlanOfCare.objects.filter(admission=admission)
                if data:
                    plans_table = PlanOfCareTable(data)
                    plans_table.paginate(page=request.GET.get("page", 1), per_page=5)
                    context['table'] = plans_table
                else:
                    context['table'] = None
            except Admission.DoesNotExist:
                context['table'] = None
        return context

class PlanOfCareCreate(LoginRequiredMixin, BSModalCreateView):
    model = PlanOfCare
    form_class = PlanOfCareCreateForm
    success_message = 'Plan Of Care was created.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_form(self, *args, **kwargs):
        form = super(PlanOfCareCreate, self).get_form(*args, **kwargs)
        if 'pk' in self.kwargs:
            try:
                admission = Admission.objects.get(id=self.kwargs['pk'])
                form.fields['admission'].initial = admission
                self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
            except Admission.DoesNotExist:
                pass
        return form

    def get_context_data(self, **kwargs):
        context = super(PlanOfCareCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create Plan of Care'
        context['btn'] = 'Create'
        return context

class PlanOfCareUpdate(LoginRequiredMixin, BSModalUpdateView):
    model = PlanOfCare
    form_class = PlanOfCareCreateForm
    template_name = 'plan_of_care/planofcare_form.html'
    success_message = 'Plan Of Care was updated.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_object(self, *args, **kwargs):
        plan = super(PlanOfCareUpdate, self).get_object(*args, **kwargs)
        admission = plan.admission
        #added_by = self.request.user
        self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
        return plan 

    def get_context_data(self, **kwargs):
        context = super(PlanOfCareUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Update Plan Of Care'
        context['btn'] = 'Update'
        return context

class PlanOfCareDelete(LoginRequiredMixin, BSModalDeleteView):
    model = PlanOfCare
    success_message = 'Plan Of Care deleted.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_object(self, *args, **kwargs):
        plan = super(PlanOfCareDelete, self).get_object(*args, **kwargs)
        admission = plan.admission
        self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
        return plan

templates/plan_of_care/includes/management_tablist.html
<h4 class="text-center">Management</h4>
<!-- Tabs navs -->
<ul class="nav nav-tabs mb-3" id="tl-management" role="tablist">
  <li class="nav-item" role="presentation">
    <a
      class="nav-link active"
      id="management-tab-1"
      data-mdb-toggle="tab"
      href="#management-tabs-1"
      role="tab"
      aria-controls="management-tabs-1"
      aria-selected="true"
      >Medications</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="management-tab-2"
      data-mdb-toggle="tab"
      href="#management-tabs-2"
      role="tab"
      aria-controls="management-tabs-2"
      aria-selected="false"
      >Plan of Care</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="management-tab-3"
      data-mdb-toggle="tab"
      href="#management-tabs-3"
      role="tab"
      aria-controls="management-tabs-3"
      aria-selected="false"
      >Problems</a
    >
  </li>
</ul>
<!-- Tabs navs -->

<div class="spinner1">
  <div class="d-flex align-items-center">
    <strong>Loading...</strong>
    <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="management-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<!-- Tabs content -->
<div class="tab-content" id="management-content">
  <div
    class="tab-pane fade active show"
    id="management-tabs-1"
    role="tabpanel"
    aria-labelledby="management-tab-1"
  >
    <div id="medications"></div>
    <div class="spinner2">
      <div class="d-flex align-items-center">
        <strong>Loading...</strong>
        <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
      </div>
    </div> 
    <!-- Create Medication button -->
    <button id="create-medication" class="btn btn-primary" type="button" name="button">Create Medication</button>   
  </div>
  <div class="tab-pane fade" id="management-tabs-2" role="tabpanel" aria-labelledby="management-tab-2">
    <div id="planofcare"></div>
    <div class="spinner2">
      <div class="d-flex align-items-center">
        <strong>Loading...</strong>
        <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
      </div>
    </div>
    <!-- Create Plan Of Care button -->
    <button id="create-planofcare" class="btn btn-primary" type="button" name="button">Create Plan Of Care</button>    
  </div>
  <div class="tab-pane fade" id="management-tabs-3" role="tabpanel" aria-labelledby="management-tab-3">
    <div id="problems"></div>
    <div class="spinner2">
      <div class="d-flex align-items-center">
        <strong>Loading...</strong>
        <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
      </div>
    </div>
    <!-- Create Problem button -->
    <button id="create-problem" class="btn btn-primary" type="button" name="button">Create Problem</button>    
  </div>
</div>
<!-- Tabs content -->

templates/plan_of_care/includes/plan_of_care.html
{% if table %}
  {% load django_tables2 %}
  {% render_table table %}
{% else %}
  <div class="alert alert-dismissible alert-info fade show">
    <button type="button" class="close">&times;</button>
    <h4 class="alert-heading">Heads up!</h4>
    <p class="mb-0">No care plans to show. <a href="{% url 'plan_of_care_admin:index' %}" class="alert-link">Create</a> one now.</p>
  </div>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {
    
    const planUpdate = $(this).find('.update-plan');
    const planDelete = $(this).find('.delete-plan');
    
    planUpdate.each(function () {
      $(this).modalForm({formURL: $(this).attr('href'), modalID: "#management-modal"});
      $(this).removeAttr('href');
    }); 
    
    planDelete.each(function () {
      $(this).modalForm({formURL: $(this).attr('href'), modalID: "#management-modal"});
      $(this).removeAttr('href');
    });
});
</script>

templates/plan_of_care/planofcare_confirm_delete.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Plan Of Care</h3>
    <button type="button" class="close" data-mdb-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete Plan Of Care of
      <strong>{{ planofcare }}</strong>?</p>
  </div>

  <div class="modal-footer">
  {% if perms.plan_of_care.delete_planofcare %}
    <button type="submit" class="btn btn-danger">Delete</button>
  {% else %}
    <a class="btn btn-danger disabled">Delete</a>
  {% endif %}
  </div>

</form>

templates/plan_of_care/planofcare_form.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">{{ title }}</h3>
    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
    {% if perms.plan_of_care.change_planofcare %}
      <button type="submit" class="btn btn-primary">{{ btn }}</button>
    {% else %}
      <a class="btn btn-primary disabled">{{ btn }}</a>
    {% endif %}
  </div>
</form>